"""Integration-vector gate (pass two, leg 2).

Run: python3 -m tests.test_integration

Integration vectors are written by a foreign writer (exp1-runner chain.py)
and cannot be regenerated by CI, so the gate CI holds is threefold per
committed pair: SHA-256 hash match against golden/integration-manifest.json,
verdict replay through the verifier's own reader, and byte-determinism of
the verdict record across two runs. These vectors confirm integration; the
hand-derived v-series carries the conviction.
"""

import hashlib
import json
import os

from fccverify import verdict

HERE = os.path.dirname(__file__)
GOLDEN = os.path.join(HERE, "..", "golden")


def _sha256(path):
    with open(path, "rb") as fh:
        return hashlib.sha256(fh.read()).hexdigest()


def _read(name):
    with open(os.path.join(GOLDEN, name), "rb") as fh:
        return fh.read()


def main():
    with open(os.path.join(GOLDEN, "integration-manifest.json")) as fh:
        manifest = json.load(fh)
    assert manifest, "empty integration manifest"
    for entry in manifest:
        cp = os.path.join(GOLDEN, entry["name"])
        rp = os.path.join(GOLDEN, entry["refuter"])
        assert _sha256(cp) == entry["sha256"], (
            "%s drifted from its manifest hash" % entry["name"])
        assert _sha256(rp) == entry["refuter_sha256"], (
            "%s drifted from its manifest hash" % entry["refuter"])
        claim = _read(entry["name"])
        ref = _read(entry["refuter"])
        v = verdict.adjudicate(claim, refuter_bytes=ref, attempt_count=1)
        assert v.verdict == entry["expected"], (
            "%s: expected %s got %s" % (entry["name"], entry["expected"],
                                        v.verdict))
        assert v.cause == entry["cause"], (
            "%s: expected cause %s got %s" % (entry["name"], entry["cause"],
                                              v.cause))
        r1 = json.dumps(v.as_record(), sort_keys=True)
        r2 = json.dumps(verdict.adjudicate(
            claim, refuter_bytes=ref, attempt_count=1).as_record(),
            sort_keys=True)
        assert r1 == r2, "%s: record not byte-identical" % entry["name"]
        print("  %-34s hash ok, %s, deterministic"
              % (entry["name"], v.verdict))
    print("\nall integration tests passed (%d pairs)" % len(manifest))


if __name__ == "__main__":
    main()
